language:
  - python

python:
  - "2.7"

sudo:
  - required

install:
  - sudo pip install 'requests[security]'
  - sudo pip install ansible

script:
  # Fix layout
  - cd ..
  - mv ansible-socoroo socorro
  - cd socorro

  - python --version

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run local test
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # Run again
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
