# Copyright (c) 2016, Quantitative Engineering Design Inc.
# All Rights Reserved.

---

- hosts: vagrant
  gather_facts: False
  tasks:
    - name: dump Vagrant ssh config (vagrant only)
      when: inventory_hostname=='vagrant'
      become: False
      local_action: shell vagrant ssh-config > vagrant-ssh-conf
                    chdir="{{ playbook_dir }}"

- hosts: socorro vagrant
  tasks:
    - name: Create 'socorro' group
      become: yes
      group:
        name=socorro
    - name: Create 'socorro' user
      become: yes
      user:
        name=socorro
        group=socorro

- hosts: socorro vagrant
  become_user: socorro
  become: yes
  roles:
    - socorro
  vars:
    socorro_upload_testing_symbols:
      - demoapp.sym
      - libMakeSegv.so.sym
