---
- hosts: socorro
  tasks:
    - name: Create 'socorro' group
      become: yes
      group:
        name=socorro
    - name: Create 'socorro' user
      become: yes
      user:
        name=socorro
        group=socorro

- hosts: socorro
  become_user: socorro
  become: yes
  roles:
    - socorro
  vars:
    socorro_upload_testing_symbols:
      - demoapp.sym
      - libMakeSegv.so.sym
