# Copyright (c) 2016, Quantitative Engineering Design Inc.
# All Rights Reserved.

---

- include: system.yml

- include: remove_honcho.yml

- include: elasticsearch.yml

- name: Check port 5000
  command: lsof -i :5000
  register: x
  ignore_errors: yes
  become: yes
  become_user: root
- debug: msg="{{ x.stdout_lines }}"

- name: Check port 9200
  command: lsof -i :9200
  register: x
  ignore_errors: yes
  become: yes
  become_user: root
- debug: msg="{{ x.stdout_lines }}"

- name: Check port 5601
  command: lsof -i :5601
  register: x
  ignore_errors: yes
  become: yes
  become_user: root
- debug: msg="{{ x.stdout_lines }}"

- include: kibana.yml

- include: socorro.yml

- include: nginx.yml

# Needed for "Setup Elasticsearch database"
- meta: flush_handlers

- name: Waiting for Elasticsearch port
  wait_for:
    port: 9200
    delay: 10

- name: Setup Elasticsearch database
  command: python ./setup_supersearch_app.py --elasticsearch.elasticsearch.elasticsearch_index=socorro_reports --resource.elasticsearch.elasticsearch_index=socorro_reports
  args:
    chdir: "{{ socorro_working_dir }}/scripts"
  environment:
    PATH: "{{ socorro_virtualenv_bin_dir }}:{{ ansible_env.PATH }}"
    VIRTUAL_ENV: ""

- meta: flush_handlers

- name: Waiting for collector port
  wait_for:
    port: 5000
    delay: 10

- include: test.yml

- debug:
    msg:
      - "Visit http://{{ inventory_hostname }}:8000 and search for 'socorro_reports'"
      - "Upload crash dumps to http://{{ inventory_hostname }}:5000/submit"
      - "Symbol files are stored in {{ socorro_symbols_dir }}"
      - "First line of symbols file contains important information"
      - "/etc/nginx/kibana-passwords contains credentials to access Kibana"
      - "Make sure that port 5601 is accessible only from localhost."