# Copyright (c) 2016, Quantitative Engineering Design Inc.
# All Rights Reserved.

---

- name: Create dhparams.pem if not present
  command: openssl dhparam -out /etc/ssl/private/dhparams.pem 2048 creates=/etc/ssl/private/dhparams.pem
  become: yes
  become_user: root

- name: Put out cert for SSL
  no_log: True  # there are private keys in this keys, don't put it on console
  copy:
    src: "ssl_certs/{{ ssl_cert | basename }}"
    dest: "{{ ssl_cert }}"
    mode: 0644
    owner: root
    group: root
  become: yes
  become_user: root
  notify:
    - restart nginx

- name: Put out key for SSL
  no_log: True  # there are private keys in this keys, don't put it on console
  copy:
    content: "{{ ssl_key_content }}"
    dest: "{{ ssl_key }}"
    mode: 0600
    owner: root
    group: root
  become: yes
  become_user: root
  notify:
    - restart nginx

- name: Configure Nginx for Socorro Collector
  template:
    src=nginx-collector.conf.j2
    dest=/etc/nginx/sites-available/collector.conf
    backup=yes
  become: yes
  become_user: root
  notify:
    - restart nginx

- name: Enable Nginx for Socorro Collector
  file:
    src=/etc/nginx/sites-available/collector.conf
    dest=/etc/nginx/sites-enabled/collector.conf
    state=link
  become: yes
  become_user: root
  notify:
    - restart nginx

- name: Configure Nginx for Kibana
  template:
    src=nginx-kibana.conf.j2
    dest=/etc/nginx/sites-available/kibana.conf
    backup=yes
  become: yes
  become_user: root
  notify:
    - restart nginx

- name: Add passwords database
  template:
    src=passwords-template.j2
    dest=/etc/nginx/kibana-passwords
    backup=yes
    mode=400
    owner=www-data
    force=no
  become: yes
  become_user: root
  notify:
    - restart nginx

- name: Enable Nginx for Kibana
  file:
    src=/etc/nginx/sites-available/kibana.conf
    dest=/etc/nginx/sites-enabled/kibana.conf
    state=link
  become: yes
  become_user: root
  notify:
    - restart nginx
